pybullet build time: Jan  5 2023 16:13:30
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:
Link name is not unique, link names in the same model have to be uniqueb3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:
iTraceback (most recent call last):
  File "simulate.py", line 16, in <module>
    simulation = SIMULATION(directOrGUI, solutionID)
  File "/Users/catherineguo/Documents/GitHub/mybots/simulation.py", line 21, in __init__
    self.robot = ROBOT(solutionID)
  File "/Users/catherineguo/Documents/GitHub/mybots/robot.py", line 11, in __init__
    self.robotId = p.loadURDF("body.urdf")
pybullet.error: Cannot load URDF file.
